import { StyleSheet } from 'react-native';
import { colors, lightColors, darkColors, ColorKey } from './colors';
import { radius, spacing } from './layout';

const getColor = (colorKey: ColorKey, mode: 'light' | 'dark') => {
  return mode === 'dark' ? darkColors[colorKey] : lightColors[colorKey];
};

export function getCardStyles(mode: 'light' | 'dark') {
  return StyleSheet.create({
    bankCard: {
      alignSelf: 'center',
      borderRadius: 12,
      height: 135,
      justifyContent: 'space-between',
      padding: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      width: 260,
    },
    bankCardBottom: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    bankCardExpiry: {
      color: getColor('whiteText', mode),
      fontSize: 16,
      fontWeight: '400',
    },
    bankCardMiddle: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: spacing.md,
    },
    bankCardNumber: {
      color: getColor('whiteText', mode),
      fontSize: 18,
      fontWeight: '500',
      letterSpacing: 2,
    },
    bankCardOwner: {
      color: getColor('whiteText', mode),
      flex: 1,
      fontSize: 16,
      fontWeight: '400',
      marginRight: spacing.md,
    },
    bankCardTitle: {
      color: getColor('whiteText', mode),
      flex: 1,
      fontSize: 18,
      fontWeight: '600',
      marginRight: spacing.md,
    },
    bankCardTop: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: spacing.md,
    },
    card: {
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
    },
    cardHover: {
      shadowOpacity: 0.08,
      shadowRadius: 12,
    },
    checkMark: {
      color: getColor('whiteText', mode),
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    colorCircle: {
      alignItems: 'center',
      borderRadius: 20,
      height: 35,
      justifyContent: 'center',
      marginRight: spacing.md,
      width: 35,
    },
    colorRow: {
      flexDirection: 'row',
      marginBottom: spacing.lg,
      marginTop: spacing.sm,
    },
    credentialCard: {
      alignItems: 'center',
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderStyle: 'solid',
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: spacing.xs,
      padding: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      width: '100%',
    },
    credentialCardInfo: {
      flexDirection: 'column',
      gap: 2,
      maxWidth: 200,
      minWidth: 0,
    },
    credentialCardLeft: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    credentialCardTitle: {
      color: getColor('primary', mode),
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '600',
    },
    credentialCardUsername: {
      color: getColor('secondary', mode),
      flexShrink: 1,
      fontSize: 12,
    },
    generatedPasswordCard: {
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: 'column',
      marginBottom: spacing.sm,
      padding: spacing.md,
    },
    iconContainer: {
      alignItems: 'center',
      backgroundColor: getColor('white', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: 10,
      borderWidth: 1,
      height: 35,
      justifyContent: 'center',
      width: 35,
    },
    iconContainerNoBg: {
      backgroundColor: 'transparent',
    },
    iconLetter: {
      color: getColor('tertiary', mode),
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 35,
      textAlign: 'center',
      width: '100%',
    },
    menuCard: {
      backgroundColor: getColor('secondaryBackground', mode),
      borderRadius: radius.md,
      flexDirection: 'column',
      marginBottom: spacing.sm,
      padding: spacing.sm,
    },
    menuIcon: {
      alignItems: 'center',
      height: 24,
      justifyContent: 'center',
      marginRight: spacing.md,
      width: 24,
    },
    menuItem: {
      alignItems: 'center',
      borderWidth: 0,
      flexDirection: 'row',
      height: 35,
      justifyContent: 'flex-start',
      marginBottom: spacing.sm,
      outline: 'none',
      position: 'relative',
      textAlign: 'left',
      width: '100%',
    },
    menuLabel: {
      color: getColor('primary', mode),
      flex: 1,
      fontSize: 14,
      fontWeight: '400',
    },
    optionRow: {
      alignItems: 'center',
      color: getColor('primary', mode),
      flexDirection: 'row',
      fontSize: 14,
      justifyContent: 'space-between',
      marginBottom: spacing.sm,
    },
    optionText: {
      color: getColor('primary', mode),
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
    },
    optionsSection: {
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: 'column',
      marginBottom: spacing.sm,
      padding: spacing.md,
    },
    passwordDisplay: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: spacing.sm,
    },
    passwordText: {
      backgroundColor: getColor('primaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderWidth: 1,
      color: getColor('secondary', mode),
      flex: 1,
      fontFamily: 'Monaco, Menlo, Ubuntu Mono, monospace',
      fontSize: 16,
      minHeight: 20,
      padding: spacing.sm,
    },
    profileCard: {
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.md,
      borderWidth: 1,
      padding: spacing.sm,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
    },
    profileCardUserDetails: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: spacing.sm,
    },
    profileCardUserEmail: {
      color: getColor('primary', mode),
      fontSize: 16,
      fontWeight: '500',
    },
    profileCardUserIcon: {
      alignItems: 'center',
      backgroundColor: getColor('secondaryBackground', mode),
      borderRadius: 25,
      color: getColor('primary', mode),
      fontSize: 24,
      height: 50,
      justifyContent: 'center',
      marginRight: spacing.sm,
      width: 50,
    },
    secureNoteCard: {
      alignItems: 'center',
      backgroundColor: getColor('secondaryBackground', mode),
      borderRadius: 20,
      flexDirection: 'row',
      height: 60,
      marginBottom: spacing.sm,
      maxWidth: 500,
      paddingLeft: spacing.md,
      paddingRight: spacing.md,
      width: '100%',
    },
    secureNoteColor: {
      borderRadius: 25,
      height: 22,
      marginRight: 15,
      width: 22,
    },
    secureNoteTitle: {
      color: getColor('primary', mode),
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
    },
    skeletonAvatar: {
      backgroundColor: getColor('disabled', mode),
      borderRadius: 10,
      height: 35,
      marginRight: spacing.sm,
      width: 35,
    },
    skeletonCard: {
      alignItems: 'center',
      backgroundColor: getColor('secondaryBackground', mode),
      borderColor: getColor('borderColor', mode),
      borderRadius: radius.lg,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: spacing.xs,
      padding: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
    },
    skeletonInfo: {
      flex: 1,
      flexDirection: 'column',
      marginBottom: spacing.xs,
    },
    skeletonTitle: {
      backgroundColor: getColor('disabled', mode),
      borderRadius: 6,
      height: 12,
      marginBottom: spacing.xs,
      width: '60%',
    },
    skeletonUsername: {
      backgroundColor: getColor('disabled', mode),
      borderRadius: 6,
      height: 12,
      width: '40%',
    },
  });
}

// Default export for backward compatibility (light mode)
export const cardStyles = getCardStyles('light'); 