import {
  MdLaunch,
  MdEmail,
  MdCopyAll,
  MdSearch,
  MdContentCopy,
  MdHomeFilled,
  MdSettings,
  MdAdd,
  MdPassword,
  MdCreditCard,
  MdLoop,
  MdHelpOutline,
  MdRefresh,
  MdPerson,
  MdSecurity,
  MdDownload,
  MdWorkspacePremium,
  MdLanguage,
  MdInfoOutline,
  MdKeyboardArrowRight,
  MdKeyboardArrowDown,
  MdArrowForwardIos,
  MdArrowBackIos,
  MdVisibility,
  MdVisibilityOff,
  MdCheckCircle,
  MdNotes,
  MdWbSunny,
  MdNightlightRound,
  MdAddCircle,
  MdClose,
  MdError,
  MdWarning,
} from 'react-icons/md';

export const IconsMap = {
  launch: MdLaunch,
  email: MdEmail,
  copyAll: MdCopyAll,
  search: MdSearch,
  copy: MdContentCopy,
  home: MdHomeFilled,
  settings: MdSettings,
  add: MdAdd,
  password: MdPassword,
  creditCard: MdCreditCard,
  loop: MdLoop,
  help: MdHelpOutline,
  refresh: MdRefresh,
  person: MdPerson,
  security: MdSecurity,
  download: MdDownload,
  workspacePremium: MdWorkspacePremium,
  language: MdLanguage,
  info: MdInfoOutline,
  arrowRight: MdKeyboardArrowRight,
  arrowDown: MdKeyboardArrowDown,
  arrowForward: MdArrowForwardIos,
  arrowBack: MdArrowBackIos,
  visibility: MdVisibility,
  visibilityOff: MdVisibilityOff,
  checkCircle: MdCheckCircle,
  note: MdNotes,
  sun: MdWbSunny,
  moon: MdNightlightRound,
  addCircle: MdAddCircle,
  close: MdClose,
  error: MdError,
  warning: MdWarning,
} as const;

export type IconKey = keyof typeof IconsMap;
