import {
    MdLaunch,
    MdEmail,
    MdCopyAll,
    MdSearch,
    MdContentCopy,
    MdHomeFilled,
    MdSettings,
    MdAdd,
    MdPassword,
    MdCreditCard,
    MdStickyNote2,
    MdLoop,
    MdHelpOutline,
    MdRefresh,
    MdPerson,
    MdSecurity,
    MdDownload,
    MdWorkspacePremium,
    MdLanguage,
    MdInfoOutline,
    MdKeyboardArrowRight,
    MdKeyboardArrowDown,
    MdArrowForwardIos,
    MdVisibility,
    MdVisibilityOff,
  } from 'react-icons/md';
  
  export const IconsMap = {
    launch: MdLaunch,
    email: MdEmail,
    copyAll: MdCopyAll,
    search: MdSearch,
    copy: MdContentCopy,
    home: MdHomeFilled,
    settings: MdSettings,
    add: MdAdd,
    password: MdPassword,
    creditCard: MdCreditCard,
    stickyNote: MdStickyNote2,
    loop: MdLoop,
    help: MdHelpOutline,
    refresh: MdRefresh,
    person: MdPerson,
    security: MdSecurity,
    download: MdDownload,
    workspacePremium: MdWorkspacePremium,
    language: MdLanguage,
    info: MdInfoOutline,
    arrowRight: MdKeyboardArrowRight,
    arrowDown: MdKeyboardArrowDown,
    arrowForward: MdArrowForwardIos,
    visibility: MdVisibility,
    visibilityOff: MdVisibilityOff,
  } as const;
  
  export type IconKey = keyof typeof IconsMap;
  